smash> smash> smash error: fg: job-id 2 does not exist
smash> smash error: fg: jobs list is empty
smash> /tmp/smash_test
smash: got ctrl-Z
smash> drzlrzrmpjhubsnzorrk> /tmp/smash_test
drzlrzrmpjhubsnzorrk> drzlrzrmpjhubsnzorrk> smash: got ctrl-Z
smash error: fg: jobs list is empty
drzlrzrmpjhubsnzorrk> smash pid is \d+
smash: got ctrl-Z
drzlrzrmpjhubsnzorrk> /tmp/smash_test/sub1
drzlrzrmpjhubsnzorrk> gfbfb> smash error: bg: job-id 19 does not exist
gfbfb> smash: got ctrl-C
smash error: bg: there is no stopped jobs to resume
gfbfb> smash error: kill: job-id 19 does not exist
gfbfb> /tmp/smash_test/sub1
smash: got ctrl-C
gfbfb> smash error: open failed: No such file or directory
gfbfb> smash error: bg: job-id 11 does not exist
gfbfb> smash: /tmp/smash_test/my_sleep was copied to /tmp/smash_test/sub2/subsub2/ywvjsukvevdrkez
gfbfb> gfbfb> smash: got ctrl-Z
smash error: kill: job-id 19 does not exist
gfbfb> gfbfb> gfbfb> smash error: fg: job-id 16 does not exist
gfbfb> smash error: bg: job-id 7 does not exist
gfbfb> smash error: fg: job-id 6 does not exist
gfbfb> smash error: chdir failed: No such file or directory
gfbfb> gfbfb> gfbfb> gfbfb> UmVhbEZydWl0Cg==
bupnxbiu> smash error: bg: job-id 19 does not exist
bupnxbiu> zvqsmsvwcvtutylbcalh> /tmp/smash_test/sub3
zvqsmsvwcvtutylbcalh> eewkbjorohnwllzu> eewkbjorohnwllzu> smash: /tmp/smash_test/random2.txt was copied to /tmp/smash_test/sub1/subsub1/clu
smash: got ctrl-Z
smash error: fg: jobs list is empty
eewkbjorohnwllzu> eewkbjorohnwllzu> eewkbjorohnwllzu> cu> /tmp/smash_test/sub3
cu> smash error: bg: there is no stopped jobs to resume
cu> /tmp/smash_test/sub3
cu> cu> cu> smash error: open failed: No such file or directory
smash: got ctrl-Z
cu> cu> /bin/bash: ls/tmp/smash_test/sub2/subsub2: No such file or directory
cu> zrvgqcikufrmyki> zrvgqcikufrmyki> smash pid is \d+
zrvgqcikufrmyki> smash error: fg: jobs list is empty
zrvgqcikufrmyki> zrvgqcikufrmyki> smash error: bg: there is no stopped jobs to resume
zrvgqcikufrmyki> zrvgqcikufrmyki> smash error: bg: there is no stopped jobs to resume
zrvgqcikufrmyki> /bin/nano
zrvgqcikufrmyki> zrvgqcikufrmyki> zrvgqcikufrmyki> oiicuea> xpaqnwzy> /bin/bash: ls/tmp/smash_test/sub1: No such file or directory
xpaqnwzy> /tmp/smash_test/sub1/subsub1/last
xpaqnwzy> /bin/nano
xpaqnwzy> /tmp/smash_test/sub1/subsub1/last
xpaqnwzy> smash error: bg: job-id 14 does not exist
xpaqnwzy> smash error: kill: job-id 7 does not exist
xpaqnwzy> smash: got ctrl-C
xpaqnwzy> smash: sending SIGKILL signal to 0 jobs:
