smash> smash: got ctrl-Z
smash error: chdir failed: No such file or directory
smash> fl> fl> wkakrbwcedqfftujxiqs> smash error: fg: job-id 20 does not exist
wkakrbwcedqfftujxiqs> aqdufxgbbmfswdclof> /tmp/smash_test/sub1
aqdufxgbbmfswdclof> otlpkgnllyld> otlpkgnllyld> smash error: bg: there is no stopped jobs to resume
otlpkgnllyld> smash error: fg: jobs list is empty
otlpkgnllyld> smash: got ctrl-C
smash error: fg: job-id 11 does not exist
otlpkgnllyld> smash: got ctrl-Z
otlpkgnllyld> /tmp/smash_test/sub1
otlpkgnllyld> smash: got ctrl-C
/tmp/smash_test/sub1
otlpkgnllyld> smash error: open failed: No such file or directory
otlpkgnllyld> otlpkgnllyld> smash error: fg: job-id 13 does not exist
otlpkgnllyld> smash error: kill: job-id 19 does not exist
otlpkgnllyld> 6
otlpkgnllyld> otlpkgnllyld> smash: /tmp/smash_test/random2.txt was copied to /tmp/smash_test/sub1/subsub1/zrxbkenbzyeflycscloq
cdqtfbvfgspfb> cdqtfbvfgspfb> cdqtfbvfgspfb> yexvbxsyzjdjwq> yexvbxsyzjdjwq> yexvbxsyzjdjwq> smash: /tmp/smash_test/random1.txt was copied to /tmp/smash_test/sub1/xzkptevunjeqcgeaaly
yexvbxsyzjdjwq> smash pid is \d+
yexvbxsyzjdjwq> smash error: fg: job-id 15 does not exist
yexvbxsyzjdjwq> smash: got ctrl-C
smash error: kill: job-id 13 does not exist
yexvbxsyzjdjwq> smash: got ctrl-C
voygdpsdaiv> smash pid is \d+
voygdpsdaiv> voygdpsdaiv> smash error: fg: job-id 20 does not exist
voygdpsdaiv> smash error: fg: job-id 6 does not exist
voygdpsdaiv> voygdpsdaiv> /bin/bash: ls/tmp/smash_test/sub2/subsub2: No such file or directory
s> smash: got ctrl-C
/tmp/smash_test/sub3
s> smash pid is \d+
s> smash error: fg: job-id 13 does not exist
s> smash error: bg: there is no stopped jobs to resume
s> smash: got ctrl-C
smash: /tmp/smash_test/random2.txt was copied to /tmp/smash_test/sub1/ftje
s> smash error: bg: there is no stopped jobs to resume
s> smash pid is \d+
s> smash error: open failed: No such file or directory
s> smash: got ctrl-C
s> smash: got ctrl-Z
s> UmVhbEZydWl0Cg==
smash: got ctrl-C
smash pid is \d+
s> /tmp/smash_test/sub3
s> smash error: bg: job-id 15 does not exist
s> smash error: kill: job-id 12 does not exist
s> s> UmVhbEZydWl0Cg==
s> bxjlttbwh> bxjlttbwh> smash error: open failed: No such file or directory
bxjlttbwh> /tmp/smash_test/sub2/subsub2
bxjlttbwh> smash: /tmp/smash_test/my_sleep was copied to /tmp/smash_test/sub1/subsub1/nqquemakiojoh
bxjlttbwh> smash error: bg: there is no stopped jobs to resume
bxjlttbwh> /bin/nano
bxjlttbwh> smash: got ctrl-C
bxjlttbwh> smash: /tmp/smash_test/random1.txt was copied to /tmp/smash_test/sub3/cxeiqmgzvrsms
bxjlttbwh> smash error: fg: job-id 6 does not exist
bxjlttbwh> bxjlttbwh> bxjlttbwh> smash: /tmp/smash_test/random1.txt was copied to /tmp/smash_test/sub1/qmqmcoeneioxxvocxmbb
bxjlttbwh> bxjlttbwh> /bin/nano
bxjlttbwh> smash: got ctrl-Z
smash error: bg: job-id 18 does not exist
bxjlttbwh> smash error: fg: jobs list is empty
bxjlttbwh> aczncpdufsaupdygmm> /bin/bash: ls/tmp/smash_test/sub1/subsub1/last: No such file or directory
aczncpdufsaupdygmm> smash error: kill: job-id 3 does not exist
aczncpdufsaupdygmm> smash error: bg: there is no stopped jobs to resume
aczncpdufsaupdygmm> xvtgwbepyowbgligap> smash: got ctrl-Z
xvtgwbepyowbgligap> smash error: bg: there is no stopped jobs to resume
xvtgwbepyowbgligap> smash: sending SIGKILL signal to 0 jobs:
