smash> smash> smash error: kill: job-id 16 does not exist
smash> smash> smash error: bg: there is no stopped jobs to resume
smash> smash: /tmp/smash_test/my_sleep was copied to /tmp/smash_test/sub1/subsub1/last/vdcfetjrcotti
smash> smash> smash> /bin/bash: ls/tmp/smash_test/doesntexit: No such file or directory
eelczy> z> smash pid is \d+
z> vqerwbsx> smash pid is \d+
vqerwbsx> smash error: bg: there is no stopped jobs to resume
vqerwbsx> smash error: kill: job-id 14 does not exist
vqerwbsx> smash error: bg: there is no stopped jobs to resume
vqerwbsx> smash error: bg: there is no stopped jobs to resume
vqerwbsx> vqerwbsx> smash error: kill: job-id 4 does not exist
vqerwbsx> smash: got ctrl-C
smash: got ctrl-C
smash error: bg: there is no stopped jobs to resume
vqerwbsx> /bin/bash: ls/tmp/smash_test/sub2/subsub2: No such file or directory
vqerwbsx> smash pid is \d+
vqerwbsx> smash error: kill: job-id 19 does not exist
vqerwbsx> /tmp/smash_test/sub2/subsub2
vqerwbsx> smash: got ctrl-C
vqerwbsx> smash: /tmp/smash_test/random2.txt was copied to /tmp/smash_test/sub1/subsub1/last/ixdzmhlmm
vqerwbsx> smash: got ctrl-C
smash error: fg: job-id 4 does not exist
vqerwbsx> smash error: kill: job-id 4 does not exist
vqerwbsx> /tmp/smash_test/sub2/subsub2
vqerwbsx> vqerwbsx> vqerwbsx> smash: got ctrl-C
smash error: bg: there is no stopped jobs to resume
vqerwbsx> smash error: open failed: No such file or directory
vqerwbsx> smash error: kill: job-id 16 does not exist
vqerwbsx> vqerwbsx> 6
dpwmpwalhu> dpwmpwalhu> smash pid is \d+
dpwmpwalhu> dpwmpwalhu> smash: got ctrl-Z
smash error: bg: there is no stopped jobs to resume
dpwmpwalhu> smash error: fg: job-id 5 does not exist
dpwmpwalhu> smash error: bg: job-id 3 does not exist
dpwmpwalhu> dpwmpwalhu> smash error: kill: job-id 3 does not exist
dpwmpwalhu> smash error: open failed: No such file or directory
dpwmpwalhu> /tmp/smash_test/sub2/subsub2
dpwmpwalhu> smash error: fg: jobs list is empty
dpwmpwalhu> dpwmpwalhu> smash: got ctrl-Z
dpwmpwalhu> dpwmpwalhu> dpwmpwalhu> smash error: bg: there is no stopped jobs to resume
dpwmpwalhu> dpwmpwalhu> UmVhbEZydWl0Cg==
dpwmpwalhu> dpwmpwalhu> smash: /tmp/smash_test/random1.txt was copied to /tmp/smash_test/sub1/wfacqd
smash: got ctrl-Z
smash: got ctrl-C
dpwmpwalhu> smash error: bg: there is no stopped jobs to resume
dpwmpwalhu> smash error: bg: job-id 9 does not exist
dpwmpwalhu> smash: got ctrl-Z
smash error: kill: job-id 11 does not exist
dpwmpwalhu> smash error: kill: job-id 2 does not exist
dpwmpwalhu> vhss> /tmp/smash_test/sub3
vhss> vhss> vhss> smash pid is \d+
vhss> UmVhbEZydWl0Cg==
vhss> smash: sending SIGKILL signal to 0 jobs:
