smash> smash error: fg: job-id 6 does not exist
smash> smash error: chdir failed: No such file or directory
smash> smash: /tmp/smash_test/random1.txt was copied to /tmp/smash_test/sub1/subsub1/jiiqfqicvjfkqjyv
smash> smash pid is \d+
smash> smash: got ctrl-Z
smash error: kill: job-id 9 does not exist
smash> meafczy> kkjgeyzzykfk> smash pid is \d+
kkjgeyzzykfk> smash error: fg: job-id 18 does not exist
kkjgeyzzykfk> smash error: cd: too many arguments
kkjgeyzzykfk> /tmp/smash_test
kkjgeyzzykfk> wbscfdrvnxes> wbscfdrvnxes> /bin/nano
wbscfdrvnxes> smash: got ctrl-Z
smash pid is \d+
wbscfdrvnxes> wbscfdrvnxes> smash error: bg: there is no stopped jobs to resume
wbscfdrvnxes> wbscfdrvnxes> smash error: kill: job-id 3 does not exist
wbscfdrvnxes> smash: got ctrl-C
smash error: kill: job-id 14 does not exist
wbscfdrvnxes> smash: got ctrl-C
smash error: open failed: No such file or directory
wbscfdrvnxes> smash: /tmp/smash_test/random2.txt was copied to /tmp/smash_test/sub1/taqvzdumocaagqfxz
wbscfdrvnxes> smash: /tmp/smash_test/random2.txt was copied to /tmp/smash_test/sub2/subsub2/vasjpvdup
wbscfdrvnxes> wbscfdrvnxes> /tmp/smash_test/sub2/subsub2
wbscfdrvnxes> smash error: fg: jobs list is empty
wbscfdrvnxes> smash error: bg: there is no stopped jobs to resume
wbscfdrvnxes> smash error: fg: jobs list is empty
wbscfdrvnxes> wbscfdrvnxes> smash: got ctrl-C
smash: got ctrl-Z
smash: got ctrl-C
wbscfdrvnxes> smash error: bg: job-id 1 does not exist
wbscfdrvnxes> smash: got ctrl-Z
smash error: fg: jobs list is empty
wbscfdrvnxes> wbscfdrvnxes> smash error: fg: jobs list is empty
wbscfdrvnxes> /bin/bash: ls/tmp/smash_test/sub3: No such file or directory
wbscfdrvnxes> smash pid is \d+
wbscfdrvnxes> 6
wbscfdrvnxes> /tmp/smash_test/sub1/subsub1
wbscfdrvnxes> cp: invalid arguments
wbscfdrvnxes> smash: got ctrl-Z
wbscfdrvnxes> smash error: fg: job-id 7 does not exist
wbscfdrvnxes> smash: got ctrl-Z
smash error: bg: job-id 15 does not exist
wbscfdrvnxes> smash: got ctrl-C
/bin/nano
wbscfdrvnxes> smash pid is \d+
wbscfdrvnxes> smash error: cd: too many arguments
wbscfdrvnxes> stwqspuqhjf> stwqspuqhjf> stwqspuqhjf> smash error: fg: job-id 6 does not exist
stwqspuqhjf> smash error: fg: jobs list is empty
stwqspuqhjf> smash error: bg: job-id 19 does not exist
stwqspuqhjf> smash: got ctrl-Z
stwqspuqhjf> /tmp/smash_test/sub1/subsub1
stwqspuqhjf> smash: /tmp/smash_test/random2.txt was copied to /tmp/smash_test/sub1/subsub1/last/kxjsyxilunqu
stwqspuqhjf> smash: got ctrl-Z
smash: got ctrl-Z
smash: got ctrl-Z
stwqspuqhjf> /bin/bash: ls/tmp/smash_test/sub3: No such file or directory
/tmp/smash_test/sub1/subsub1
stwqspuqhjf> r> r> smash error: kill: job-id 19 does not exist
r> r> lprgz> smash: /tmp/smash_test/random1.txt was copied to /tmp/smash_test/sub1/subsub1/qxcfunt
lprgz> scvtizlyfghalhwkaggz> smash error: open failed: No such file or directory
scvtizlyfghalhwkaggz> smash pid is \d+
scvtizlyfghalhwkaggz> smash error: open failed: No such file or directory
scvtizlyfghalhwkaggz> smash: sending SIGKILL signal to 0 jobs:
