smash> smash: /tmp/smash_test/random1.txt was copied to /tmp/smash_test/sub1/subsub1/dspwxezbwlccl
smash: got ctrl-C
smash: got ctrl-C
smash> smash error: bg: there is no stopped jobs to resume
smash> smash: got ctrl-Z
smash> smash> /bin/nano
smash> smash> 6
/bin/bash: ls/tmp/smash_test/sub1/subsub1: No such file or directory
smash> smash pid is \d+
smash> 6
smash> /tmp/smash_test
smash> smash> /bin/bash: ls/tmp/smash_test/sub1: No such file or directory
smash error: kill: job-id 15 does not exist
smash> smash> /bin/bash: ls/tmp/smash_test/sub2/subsub2: No such file or directory
smash> smash error: kill: job-id 2 does not exist
smash> smash> smash> /bin/nano
smash error: fg: jobs list is empty
smash> ixpa> p> p> /tmp/smash_test/sub3
p> howgsmcsgb> smash error: fg: jobs list is empty
howgsmcsgb> smash: got ctrl-C
smash: got ctrl-C
howgsmcsgb> smash: got ctrl-Z
smash error: bg: job-id 11 does not exist
howgsmcsgb> smash error: fg: job-id 3 does not exist
howgsmcsgb> smash error: fg: job-id 14 does not exist
howgsmcsgb> howgsmcsgb> smash error: fg: jobs list is empty
howgsmcsgb> smash: /tmp/smash_test/random2.txt was copied to /tmp/smash_test/sub1/subsub1/hctlarigibtcjxe
howgsmcsgb> howgsmcsgb> smash: got ctrl-C
howgsmcsgb> howgsmcsgb> smash: /tmp/smash_test/random2.txt was copied to /tmp/smash_test/sub1/subsub1/mmwldha
/tmp/smash_test/sub1/subsub1/last
smash: got ctrl-C
howgsmcsgb> smash: got ctrl-C
smash error: bg: job-id 1 does not exist
howgsmcsgb> howgsmcsgb> howgsmcsgb> howgsmcsgb> howgsmcsgb> /bin/nano
UmVhbEZydWl0Cg==
howgsmcsgb> howgsmcsgb> 6
smash error: kill: job-id 8 does not exist
howgsmcsgb> smash error: bg: there is no stopped jobs to resume
howgsmcsgb> 6
smash: got ctrl-Z
howgsmcsgb> smash error: open failed: No such file or directory
howgsmcsgb> smash error: fg: job-id 20 does not exist
howgsmcsgb> /bin/nano
howgsmcsgb> smash pid is \d+
smash: got ctrl-Z
howgsmcsgb> smash: /tmp/smash_test/random1.txt was copied to /tmp/smash_test/sub1/subsub1/last/lognqxzqhaxjxubkrult
howgsmcsgb> smash: got ctrl-C
smash error: bg: there is no stopped jobs to resume
howgsmcsgb> smash error: open failed: No such file or directory
howgsmcsgb> /tmp/smash_test/sub1/subsub1/last
howgsmcsgb> howgsmcsgb> smash pid is \d+
howgsmcsgb> smash: got ctrl-Z
howgsmcsgb> smash: got ctrl-C
howgsmcsgb> howgsmcsgb> smash: got ctrl-Z
howgsmcsgb> howgsmcsgb> smash: got ctrl-C
smash: got ctrl-C
howgsmcsgb> smash error: cd: too many arguments
howgsmcsgb> smash error: fg: job-id 6 does not exist
howgsmcsgb> UmVhbEZydWl0Cg==
smash: got ctrl-C
howgsmcsgb> howgsmcsgb> smash: /tmp/smash_test/my_sleep was copied to /tmp/smash_test/sub1/subsub1/imclylwfsodfefc
howgsmcsgb> smash: got ctrl-C
smash error: bg: there is no stopped jobs to resume
howgsmcsgb> smash error: kill: job-id 3 does not exist
howgsmcsgb> y> smash: sending SIGKILL signal to 0 jobs:
smash: got ctrl-C
smash: got ctrl-C
