smash> smash error: cd: OLDPWD not set
smash> smash error: cd: too many arguments
smash> smash: got ctrl-C
smash pid is \d+
smash> /tmp/smash_test
smash> /tmp/smash_test
smash> smash error: kill: job-id 9 does not exist
smash> smash: got ctrl-Z
smash: /tmp/smash_test/random1.txt was copied to /tmp/smash_test/sub3/puqtflonpqwvajzibh
smash> 6
smash> smash: got ctrl-Z
UmVhbEZydWl0Cg==
smash> /bin/bash: ls/tmp/smash_test/sub2: No such file or directory
smash> smash: got ctrl-C
smash: got ctrl-Z
/tmp/smash_test
smash> smash> smash error: kill: job-id 16 does not exist
smash> smash> smash: got ctrl-Z
smash: got ctrl-Z
smash error: bg: there is no stopped jobs to resume
smash> smash error: kill: job-id 2 does not exist
smash> smash> smash pid is \d+
smash> smash error: fg: jobs list is empty
smash> smash: /tmp/smash_test/random2.txt was copied to /tmp/smash_test/sub1/subsub1/last/ivrpvroixmqico
smash> smash> gtcruduvmzd> gtcruduvmzd> smash error: fg: job-id 7 does not exist
gtcruduvmzd> smash pid is \d+
gtcruduvmzd> smash error: bg: job-id 19 does not exist
gtcruduvmzd> gtcruduvmzd> smash: got ctrl-C
qclxvzgfyk> qclxvzgfyk> /bin/bash: ls/tmp/smash_test/sub1/subsub1/last: No such file or directory
qclxvzgfyk> qclxvzgfyk> UmVhbEZydWl0Cg==
gqbz> smash error: kill: job-id 7 does not exist
gqbz> smash: got ctrl-C
smash: got ctrl-Z
smash error: chdir failed: No such file or directory
gqbz> /tmp/smash_test/sub1/subsub1
gqbz> smash error: bg: there is no stopped jobs to resume
gqbz> gqbz> smash: /tmp/smash_test/random1.txt was copied to /tmp/smash_test/sub2/buefhu
gqbz> smash pid is \d+
gqbz> gqbz> xnrs> smash error: bg: there is no stopped jobs to resume
xnrs> xnrs> smash: got ctrl-C
smash: got ctrl-Z
xnrs> smash error: kill: job-id 4 does not exist
xnrs> ejyqpk> smash: /tmp/smash_test/my_sleep was copied to /tmp/smash_test/sub1/subsub1/last/iuiemsuhlnsgsbowfkb
ejyqpk> smash: /tmp/smash_test/random2.txt was copied to /tmp/smash_test/sub1/pcqczoisikton
ejyqpk> smash: /tmp/smash_test/random2.txt was copied to /tmp/smash_test/sub2/subsub2/rcuxf
ejyqpk> smash: got ctrl-C
smash: /tmp/smash_test/random2.txt was copied to /tmp/smash_test/sub1/subsub1/dehascbi
ejyqpk> smash error: kill: job-id 7 does not exist
ejyqpk> smash pid is \d+
ejyqpk> pbnlhiatkxcb> smash: got ctrl-Z
pbnlhiatkxcb> smash error: bg: there is no stopped jobs to resume
pbnlhiatkxcb> pbnlhiatkxcb> smash: got ctrl-Z
smash: got ctrl-Z
pbnlhiatkxcb> smash pid is \d+
pbnlhiatkxcb> smash: got ctrl-Z
smash: sending SIGKILL signal to 0 jobs:
