smash> smash error: bg: job-id 20 does not exist
smash> smash: got ctrl-C
smash: got ctrl-C
smash error: fg: jobs list is empty
smash> smash error: bg: job-id 9 does not exist
smash> smash: got ctrl-C
smash> smash pid is \d+
smash> smash error: kill: job-id 10 does not exist
smash> smash error: open failed: No such file or directory
smash> smash> smash: got ctrl-Z
smash error: cd: too many arguments
smash> smash error: kill: job-id 11 does not exist
smash> smash error: open failed: No such file or directory
smash> rkstncbjocpotce> /tmp/smash_test/sub1
rkstncbjocpotce> rkstncbjocpotce> rkstncbjocpotce> 6
rkstncbjocpotce> smash pid is \d+
rkstncbjocpotce> smash error: kill: job-id 18 does not exist
rkstncbjocpotce> smash pid is \d+
rkstncbjocpotce> rkstncbjocpotce> smash error: fg: jobs list is empty
rkstncbjocpotce> smash: /tmp/smash_test/random1.txt was copied to /tmp/smash_test/sub3/bb
rkstncbjocpotce> ryjlocxgskgqxczappgo> jayyvslkaopryocq> smash pid is \d+
jayyvslkaopryocq> smash: got ctrl-Z
jayyvslkaopryocq> smash error: fg: job-id 15 does not exist
jayyvslkaopryocq> smash error: bg: job-id 2 does not exist
jayyvslkaopryocq> smash: /tmp/smash_test/random2.txt was copied to /tmp/smash_test/sub2/o
jayyvslkaopryocq> zjjcjjgzvmkwmt> zjjcjjgzvmkwmt> smash: /tmp/smash_test/my_sleep was copied to /tmp/smash_test/sub1/gmzxoyokziji
zjjcjjgzvmkwmt> zjjcjjgzvmkwmt> smash pid is \d+
zjjcjjgzvmkwmt> zjjcjjgzvmkwmt> /tmp/smash_test/sub3
zjjcjjgzvmkwmt> smash error: kill: job-id 6 does not exist
zjjcjjgzvmkwmt> khwt> khwt> smash: got ctrl-Z
smash pid is \d+
khwt> smash error: bg: there is no stopped jobs to resume
khwt> smash error: cd: too many arguments
khwt> smash error: open failed: No such file or directory
khwt> smash error: fg: job-id 16 does not exist
khwt> khwt> /bin/nano
smash: got ctrl-C
khwt> smash: got ctrl-Z
smash: got ctrl-C
smash pid is \d+
khwt> khwt> smash: got ctrl-C
smash: /tmp/smash_test/my_sleep was copied to /tmp/smash_test/sub1/subsub1/last/xnjark
khwt> smash error: open failed: No such file or directory
khwt> smash pid is \d+
khwt> /tmp/smash_test/sub3
khwt> smash: got ctrl-C
smash error: bg: job-id 13 does not exist
khwt> smash: /tmp/smash_test/random1.txt was copied to /tmp/smash_test/sub1/subsub1/mrllmqsphro
khwt> smash pid is \d+
khwt> khwt> smash error: bg: there is no stopped jobs to resume
khwt> smash error: kill: job-id 4 does not exist
khwt> smash: got ctrl-C
smash error: bg: job-id 9 does not exist
khwt> smash pid is \d+
khwt> smash error: fg: jobs list is empty
khwt> khwt> smash: got ctrl-C
smash error: bg: there is no stopped jobs to resume
khwt> smash error: kill: job-id 1 does not exist
khwt> smash pid is \d+
khwt> smash: sending SIGKILL signal to 0 jobs:
